/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 24-Dec-2020 17:11:30
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型
 * 分子 长度  : 18
 * 分母 长度  : 18
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\WorkingTools\Matlab2020\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int NL = 18;
const real32_T NUM[18] = {
  0.0004793484404,   -0.002149262, 0.005930194166,    -0.01084904,  0.01534511615,
   -0.01655694097,   0.0145611912,-0.009326857515, 0.003402658505, 0.003402658505,
  -0.009326857515,   0.0145611912, -0.01655694097,  0.01534511615,    -0.01084904,
   0.005930194166,   -0.002149262,0.0004793484404
};
const int DL = 18;
const real32_T DEN[18] = {
                1,   -8.624773979,    36.39727783,    -99.0246048,    193.5945892,
     -287.6271973,    335.4121704,   -312.9385986,    236.1031342,   -144.6713867,
      71.91122437,   -28.80280495,    9.174246788,   -2.273334026,   0.4229340255,
   -0.05563091859,  0.00461706752,-0.0001817250886
};
